version = 1

[global]
dll = "/home/kloud/Documents/shared/_Personal/random_files/lsfg-vk.dll"
no_fp16 = false

[[game]]
exe = "GenshinImpact.exe"
multiplier = 3
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "benchmark"
multiplier = 4
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "vkcube"
multiplier = 20
flow_scale = 1.0
performance_mode = true
hdr_mode = false
experimental_present_mode = "fifo"
