touchpad:
  speed:
    swipe_threshold: 15
    events: 1
  delta_multiplier: 6.0

  gestures:

    - type: hold
      fingers: 3
      threshold: 800
      keyboard_modifiers: [alt]

      actions:
        - on: begin
          plasma_shortcut: kwin,Window Close

    - type: hold
      fingers: 3
      threshold: 800
      keyboard_modifiers: none

      actions:
        - on: begin
          plasma_shortcut: kwin,Window Above Other Windows

          conditions:
            - negate: [window_state]
              window_state: [fullscreen, maximized]

    - type: swipe
      fingers: 3
      direction: up_down
      keyboard_modifiers: none

      actions:
        - on: begin
          input:
            - keyboard: [+leftmeta]
            - mouse: [+left]

        - on: update
          input:
            - mouse: [move_by_delta]

        - on: end_cancel
          input:
            - keyboard: [-leftmeta]
            - mouse: [-left]

    - type: swipe
      fingers: 3
      direction: left_right
      keyboard_modifiers: [meta]

      actions:
        - on: begin
          input:
            - keyboard: [+leftmeta]
            - mouse: [+right]

        - on: update
          input:
            - mouse: [move_by_delta]

        - on: end_cancel
          input:
            - keyboard: [-leftmeta]
            - mouse: [-right]

    - type: swipe
      fingers: 3
      direction: left
      keyboard_modifiers: []

      actions:
        - on: begin
          input:
            - keyboard: [ back ]

    - type: swipe
      fingers: 3
      direction: right
      keyboard_modifiers: []

      actions:
        - on: begin
          input:
          - mouse: [ forward ]


    - type: swipe
      fingers: 3
      direction: left
      keyboard_modifiers: [alt]

      actions:
        - on: begin
          input:
          - keyboard: [leftmeta+left]

    - type: swipe
      fingers: 3
      direction: right
      keyboard_modifiers: [alt]

      actions:
        - on: begin
          input:
          - keyboard: [leftmeta+right]


    - type: swipe
      fingers: 3
      direction: left
      keyboard_modifiers: [shift]

      actions:
        - plasma_shortcut: kwin,Window One Desktop to the Left

    - type: swipe
      fingers: 3
      direction: right
      keyboard_modifiers: [shift]

      actions:
        - plasma_shortcut: kwin,Window One Desktop to the Right

    - type: swipe
      fingers: 3
      direction: left_right
      keyboard_modifiers: [alt, shift]

      actions:
        - on: update
          interval: -10
          plasma_shortcut: kmix,decrease_microphone_volume

        - on: update
          interval: 10
          plasma_shortcut: kmix,increase_microphone_volume

    - type: swipe
      fingers: 3
      direction: up_down
      keyboard_modifiers: [alt, shift]

      actions:
        - on: update
          interval: -10
          command: pactl set-sink-volume @DEFAULT_SINK@ +5%

        - on: update
          interval: 10
          command: pactl set-sink-volume @DEFAULT_SINK@ -5%

    - type: swipe
      fingers: 3
      direction: up_down
      keyboard_modifiers: [shift]

      actions:
        - on: update
          interval: -10
          plasma_shortcut: kwin,Increase Opacity

        - on: update
          interval: 10
          plasma_shortcut: kwin,Decrease Opacity

    - type: swipe
      fingers: 3
      direction: up_down
      keyboard_modifiers: [meta]

      actions:
        - on: update
          interval: -5
          plasma_shortcut: org_kde_powerdevil,Increase Screen Brightness Small

        - on: update
          interval: 5
          plasma_shortcut: org_kde_powerdevil,Decrease Screen Brightness Small


    - type: swipe
      fingers: 3
      direction: up
      keyboard_modifiers: [alt]

      actions:
        - on: begin
          one:
            - plasma_shortcut: kwin,Window Maximize
              conditions:
                - $window_maximized == false

            - plasma_shortcut: kwin,Window Fullscreen
              conditions:
                - $window_fullscreen == false


    - type: swipe
      fingers: 3
      direction: down
      keyboard_modifiers: [alt]

      actions:
        - on: begin
          one:
            - plasma_shortcut: kwin,Window Fullscreen
              conditions:
                - $window_fullscreen == true

            - plasma_shortcut: kwin,Window Maximize
              conditions:
                - $window_maximized == true

            - plasma_shortcut: kwin,Window Minimize


